import bpy
import bmesh
import mathutils
import math
import os
import struct
from mathutils import Vector

_GEOM_TYPES = {"MESH", "CURVE", "FONT", "SURFACE"}  # what we want in STL

def _iter_world_tris_any(obj):
    """Yield world-space triangles (v0,v1,v2) for any supported object via evaluated mesh."""
    deps = bpy.context.evaluated_depsgraph_get()
    eo = obj.evaluated_get(deps)
    me = eo.to_mesh()
    try:
        if not me:
            return
        me.calc_loop_triangles()
        verts = me.vertices
        M = eo.matrix_world
        for tri in me.loop_triangles:
            v0 = M @ verts[tri.vertices[0]].co
            v1 = M @ verts[tri.vertices[1]].co
            v2 = M @ verts[tri.vertices[2]].co
            yield (v0, v1, v2)
    finally:
        eo.to_mesh_clear()

def _write_binary_stl_all(path_stl: str, target_obj):
    """Addon-free writer that exports a specific object."""
    # Count triangles
    tri_count = 0
    for _ in _iter_world_tris_any(target_obj):
        tri_count += 1

    with open(path_stl, "wb") as f:
        f.write(b"Generated by Blender script".ljust(80, b"\0"))
        f.write(struct.pack("<I", tri_count))
        for v0, v1, v2 in _iter_world_tris_any(target_obj):
            n = (v1 - v0).cross(v2 - v0)
            ln = n.length
            if ln > 1e-20: n /= ln
            else:          n = Vector((0.0, 0.0, 0.0))
            f.write(struct.pack(
                "<12fH",
                float(n.x), float(n.y), float(n.z),
                float(v0.x), float(v0.y), float(v0.z),
                float(v1.x), float(v1.y), float(v1.z),
                float(v2.x), float(v2.y), float(v2.z),
                0
            ))
    print(f"[OK] Fallback STL Exported: {path_stl}")

# ==========================================
# HELPER: CREATE BOX FROM BOUNDS
# ==========================================
def create_box(name, min_bounds, max_bounds):
    """Creates a cube perfectly bounded by two 3D coordinate vectors."""
    dx = max_bounds[0] - min_bounds[0]
    dy = max_bounds[1] - min_bounds[1]
    dz = max_bounds[2] - min_bounds[2]
    
    cx = (max_bounds[0] + min_bounds[0]) / 2.0
    cy = (max_bounds[1] + min_bounds[1]) / 2.0
    cz = (max_bounds[2] + min_bounds[2]) / 2.0
    
    bpy.ops.mesh.primitive_cube_add(size=1)
    box = bpy.context.active_object
    box.name = name
    box.scale = (dx, dy, dz)
    box.location = (cx, cy, cz)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    return box

# ==========================================
# CORE 3D SPATIAL JIG FUNCTION
# ==========================================
def generate_jig_in_place(
    raw_model, 
    master_min, 
    master_max, 
    overlap, 
    bottom_thickness=1.0, 
    inflation=0.4, 
    target_tris=50000, 
    direction='+Z'
):
    print(f"\n[FUNC] Generating low-profile {direction} Jig...")
    
    # 1. Duplicate working model
    working_model = raw_model.copy()
    working_model.data = raw_model.data.copy()
    working_model.name = f"Working_Cutter_{direction}"
    bpy.context.collection.objects.link(working_model)
    bpy.context.view_layer.objects.active = working_model

    # 2. Get absolute model bounds
    bbox = [working_model.matrix_world @ mathutils.Vector(b) for b in working_model.bound_box]
    mod_min = (min(b.x for b in bbox), min(b.y for b in bbox), min(b.z for b in bbox))
    mod_max = (max(b.x for b in bbox), max(b.y for b in bbox), max(b.z for b in bbox))

    # 3. SPATIAL MAPPING LOGIC (Updated for Low-Profile Thickness)
    clearance = 5.0 
    inf = 1000.0    
    
    if direction == '+Z': # Jig on Bottom
        jig_min = (master_min[0], master_min[1], mod_min[2] - bottom_thickness)
        jig_max = (master_max[0], master_max[1], mod_min[2] + overlap)
        cut_min = (-inf, -inf, mod_min[2] + overlap + clearance)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 0, 1))
        
    elif direction == '-Z': # Jig on Top
        jig_min = (master_min[0], master_min[1], mod_max[2] - overlap)
        jig_max = (master_max[0], master_max[1], mod_max[2] + bottom_thickness)
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, inf, mod_max[2] - overlap - clearance)
        sweep_vec = mathutils.Vector((0, 0, -1))
        
    elif direction == '+X': # Jig on Left
        jig_min = (mod_min[0] - bottom_thickness, master_min[1], master_min[2])
        jig_max = (mod_min[0] + overlap, master_max[1], master_max[2])
        cut_min = (mod_min[0] + overlap + clearance, -inf, -inf)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((1, 0, 0))
        
    elif direction == '-X': # Jig on Right
        jig_min = (mod_max[0] - overlap, master_min[1], master_min[2])
        jig_max = (mod_max[0] + bottom_thickness, master_max[1], master_max[2])
        cut_min = (-inf, -inf, -inf)
        cut_max = (mod_max[0] - overlap - clearance, inf, inf)
        sweep_vec = mathutils.Vector((-1, 0, 0))
        
    elif direction == '+Y': # Jig on Front
        jig_min = (master_min[0], mod_min[1] - bottom_thickness, master_min[2])
        jig_max = (master_max[0], mod_min[1] + overlap, master_max[2])
        cut_min = (-inf, mod_min[1] + overlap + clearance, -inf)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 1, 0))
        
    elif direction == '-Y': # Jig on Back
        jig_min = (master_min[0], mod_max[1] - overlap, master_min[2])
        jig_max = (master_max[0], mod_max[1] + bottom_thickness, master_max[2])
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, mod_max[1] - overlap - clearance, inf)
        sweep_vec = mathutils.Vector((0, -1, 0))

    # 4. Trim Excessive Model
    trim_cutter = create_box(f"Trim_{direction}", cut_min, cut_max)
    bpy.context.view_layer.objects.active = working_model
    trim_mod = working_model.modifiers.new(type="BOOLEAN", name="Trim")
    trim_mod.object = trim_cutter
    trim_mod.operation = 'DIFFERENCE'
    trim_mod.solver = 'EXACT'
    bpy.ops.object.modifier_apply(modifier=trim_mod.name)
    bpy.data.objects.remove(trim_cutter, do_unlink=True)

    # 5. Simplify & Inflate
    working_model.data.calc_loop_triangles()
    if len(working_model.data.loop_triangles) > target_tris:
        decimate_mod = working_model.modifiers.new(type="DECIMATE", name="Optimize")
        decimate_mod.decimate_type = 'COLLAPSE'
        decimate_mod.ratio = target_tris / len(working_model.data.loop_triangles)
        bpy.ops.object.modifier_apply(modifier=decimate_mod.name)

    bpy.ops.object.editmode_toggle()
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.normals_make_consistent(inside=False)
    bpy.ops.object.editmode_toggle()

    disp_mod = working_model.modifiers.new(type="DISPLACE", name="Inflate")
    disp_mod.strength = inflation
    disp_mod.mid_level = 0.0
    bpy.ops.object.modifier_apply(modifier=disp_mod.name)

    # 6. Create the specific Jig Box side
    final_jig = create_box(f"Jig_{direction}", jig_min, jig_max)

    # 7. Sweep the Master Cutter
    move_distance = overlap + 2.0 
    step_size = 0.5
    steps = int(math.ceil(move_distance / step_size))

    bpy.ops.object.select_all(action='DESELECT')
    cutter_parts = []
    for i in range(steps + 1):
        dup = working_model.copy()
        dup.data = working_model.data.copy()
        bpy.context.collection.objects.link(dup)
        
        translation = sweep_vec * (i * step_size)
        dup.location.x += translation.x
        dup.location.y += translation.y
        dup.location.z += translation.z
        cutter_parts.append(dup)

    for part in cutter_parts: part.select_set(True)
    bpy.context.view_layer.objects.active = cutter_parts[0]
    bpy.ops.object.join()
    master_cutter = bpy.context.active_object

    remesh_mod = master_cutter.modifiers.new(type='REMESH', name='Fuse_Slices')
    remesh_mod.mode = 'VOXEL'
    remesh_mod.voxel_size = 0.5
    bpy.ops.object.modifier_apply(modifier=remesh_mod.name)

    # 8. Punch the cavity
    bpy.ops.object.select_all(action='DESELECT')
    bpy.context.view_layer.objects.active = final_jig

    final_cut = final_jig.modifiers.new(type="BOOLEAN", name="Jig_Cut")
    final_cut.object = master_cutter
    final_cut.operation = 'DIFFERENCE'
    final_cut.solver = 'EXACT' 
    final_cut.double_threshold = 0.0001 
    bpy.ops.object.modifier_apply(modifier=final_cut.name)

    # 9. Cleanup
    bpy.data.objects.remove(working_model, do_unlink=True)
    bpy.data.objects.remove(master_cutter, do_unlink=True)

    return final_jig

# ==========================================
# FULL 6-SIDED EXECUTION PIPELINE
# ==========================================
if __name__ == "__main__":
    import argparse
    import sys
    # Handle Blender arg passing (if run inside blender)
    argv = sys.argv[1:]
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]

    parser = argparse.ArgumentParser()
    parser.add_argument("--input_glb", type=str, required=True)
    parser.add_argument("--output_dir", type=str, required=True)
    parser.add_argument("--model_name_seed", type=str, default="model")
    parser.add_argument("--slot_center", type=float, nargs=3, required=True)
    parser.add_argument("--slot_size", type=float, nargs=2, required=True)
    parser.add_argument("--jigs_requested", type=str, default="")
    parser.add_argument("--overlap_x", type=float, default=3.0)
    parser.add_argument("--overlap_y", type=float, default=5.0)
    parser.add_argument("--overlap_z", type=float, default=5.0)
    parser.add_argument("--inflation_margin", type=float, default=0.4)
    parser.add_argument("--grid_height", type=float, default=50.0)

    args = parser.parse_args(argv)

    GLB_INPUT_PATH = args.input_glb
    os.makedirs(args.output_dir, exist_ok=True)
    BLEND_OUTPUT_PATH = os.path.join(args.output_dir, f"{args.model_name_seed}_jigs.blend")
    
    # 1. Cleanup
    bpy.ops.object.select_all(action='DESELECT')
    for obj in bpy.context.scene.objects:
        if obj.type == 'MESH': obj.select_set(True)
    bpy.ops.object.delete()

    # 2. Import and Pre-Scale
    bpy.ops.import_scene.gltf(filepath=GLB_INPUT_PATH)
    raw_model = bpy.context.selected_objects[0]
    raw_model.name = "Original_Model"
    bpy.context.view_layer.objects.active = raw_model
    
    HEIGHT = args.grid_height
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    z_height = max(b.z for b in bbox) - min(b.z for b in bbox)
    scale_factor = HEIGHT / z_height
    raw_model.scale = (scale_factor, scale_factor, scale_factor)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    # 3. Center model at slot_center
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    cx = (max(b.x for b in bbox) + min(b.x for b in bbox)) / 2.0
    cy = (max(b.y for b in bbox) + min(b.y for b in bbox)) / 2.0
    cz = (max(b.z for b in bbox) + min(b.z for b in bbox)) / 2.0
    raw_model.location = (args.slot_center[0] - cx, args.slot_center[1] - cy, args.slot_center[2] - cz)
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)

    # 4. Process Control Variables
    MASTER_X, MASTER_Y, MASTER_Z = args.slot_size[0], args.slot_size[1], args.grid_height
    master_min = (args.slot_center[0] - MASTER_X/2, args.slot_center[1] - MASTER_Y/2, args.slot_center[2] - MASTER_Z/2)
    master_max = (args.slot_center[0] + MASTER_X/2, args.slot_center[1] + MASTER_Y/2, args.slot_center[2] + MASTER_Z/2)

    OVERLAP_Z = args.overlap_z 
    BOTTOM_THICKNESS = 1.0 # The fixed backing thickness for the UV print bed

    # 5. Generate specified jigs
    if args.jigs_requested:
        directions = [d.strip() for d in args.jigs_requested.split(",") if d.strip()]
    else:
        directions = ['+Z', '-Z', '+X', '-X', '+Y', '-Y']

    for d in directions:
        final_jig = generate_jig_in_place(
            raw_model=raw_model,
            master_min=master_min,
            master_max=master_max,
            overlap=OVERLAP_Z,
            bottom_thickness=BOTTOM_THICKNESS,
            inflation=args.inflation_margin,
            direction=d
        )
        
        # Export each individual jig STL
        bpy.ops.object.select_all(action='DESELECT')
        final_jig.select_set(True)
        bpy.context.view_layer.objects.active = final_jig
        stl_path = os.path.join(args.output_dir, f"{args.model_name_seed}_jig_{d}.stl")
        
        try:
            bpy.ops.export_mesh.stl(filepath=stl_path, use_selection=True)
        except Exception as e:
            print(f"Standard STL export failed: {e}. Falling back to binary writer...")
            _write_binary_stl_all(stl_path, final_jig)

        # Export individual jig BLEND
        blend_path_single = os.path.join(args.output_dir, f"{args.model_name_seed}_jig_{d}.blend")
        # Save a copy of the current state (contains just this jig since others are generated progressively)
        # Note: If you want *only* this jig, we temporarily delete the raw model, save, and undo.
        try:
            bpy.ops.wm.save_as_mainfile(filepath=blend_path_single, copy=True)
            print(f"[OK] Individual Blend Exported: {blend_path_single}")
        except Exception as e:
            print(f"Failed to export individual blend: {e}")

    # 6. Save
    bpy.context.view_layer.update()
    bpy.ops.wm.save_as_mainfile(filepath=BLEND_OUTPUT_PATH)
    print(f"\n[SUCCESS] Low-Profile Production Jig Generation Complete!")