import bpy
import bmesh
import mathutils
import math
import os
import struct
from mathutils import Vector

_GEOM_TYPES = {"MESH", "CURVE", "FONT", "SURFACE"}  # what we want in STL

def _iter_world_tris_any(obj):
    """Yield world-space triangles (v0,v1,v2) for any supported object via evaluated mesh."""
    deps = bpy.context.evaluated_depsgraph_get()
    eo = obj.evaluated_get(deps)
    me = eo.to_mesh()
    try:
        if not me:
            return
        me.calc_loop_triangles()
        verts = me.vertices
        M = eo.matrix_world
        for tri in me.loop_triangles:
            v0 = M @ verts[tri.vertices[0]].co
            v1 = M @ verts[tri.vertices[1]].co
            v2 = M @ verts[tri.vertices[2]].co
            yield (v0, v1, v2)
    finally:
        eo.to_mesh_clear()

def _write_binary_stl_all(path_stl: str, target_obj):
    """Addon-free writer that exports a specific object."""
    # Count triangles
    tri_count = 0
    for _ in _iter_world_tris_any(target_obj):
        tri_count += 1

    with open(path_stl, "wb") as f:
        f.write(b"Generated by Blender script".ljust(80, b"\0"))
        f.write(struct.pack("<I", tri_count))
        for v0, v1, v2 in _iter_world_tris_any(target_obj):
            n = (v1 - v0).cross(v2 - v0)
            ln = n.length
            if ln > 1e-20: n /= ln
            else:          n = Vector((0.0, 0.0, 0.0))
            f.write(struct.pack(
                "<12fH",
                float(n.x), float(n.y), float(n.z),
                float(v0.x), float(v0.y), float(v0.z),
                float(v1.x), float(v1.y), float(v1.z),
                float(v2.x), float(v2.y), float(v2.z),
                0
            ))
    print(f"[OK] Fallback STL Exported: {path_stl}")

# ==========================================
# HELPER: CREATE BOX FROM BOUNDS
# ==========================================
def create_box(name, min_bounds, max_bounds):
    """Creates a cube perfectly bounded by two 3D coordinate vectors."""
    dx = max_bounds[0] - min_bounds[0]
    dy = max_bounds[1] - min_bounds[1]
    dz = max_bounds[2] - min_bounds[2]
    
    cx = (max_bounds[0] + min_bounds[0]) / 2.0
    cy = (max_bounds[1] + min_bounds[1]) / 2.0
    cz = (max_bounds[2] + min_bounds[2]) / 2.0
    
    bpy.ops.mesh.primitive_cube_add(size=1)
    box = bpy.context.active_object
    box.name = name
    box.scale = (dx, dy, dz)
    box.location = (cx, cy, cz)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    return box

# ==========================================
# HELPERS: CYLINDER PRIMITIVE + BOOLEAN OP
# ==========================================
def create_cylinder(name, radius, depth, location=(0.0, 0.0, 0.0), verts=100):
    """Creates a Z-axis cylinder of given radius/depth, centered at location."""
    bpy.ops.mesh.primitive_cylinder_add(
        radius=radius, depth=depth, location=location, vertices=verts
    )
    cyl = bpy.context.active_object
    cyl.name = name
    return cyl

def apply_boolean(target, cutter, operation='DIFFERENCE'):
    """Applies a boolean modifier to target using cutter, applies it, deletes cutter."""
    mod = target.modifiers.new(type="BOOLEAN", name=f"Bool_{operation}")
    mod.object = cutter
    mod.operation = operation
    mod.solver = 'EXACT'
    bpy.context.view_layer.objects.active = target
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(cutter, do_unlink=True)
    return target

# ==========================================
# UNIVERSAL JIG (+U / -U) POST-PROCESS
# ==========================================
def measure_model_xy_extent(model_obj, center_x, center_y, z_min, z_max):
    """
    Scans model_obj's evaluated world-space vertices between z_min and z_max
    (the Z slice of the model that actually becomes the cavity impression),
    returning the farthest X and Y distance from (center_x, center_y) found
    in that range. For a triangulated mesh the true extent always occurs at
    a vertex, so a single pass over all vertices in the window is exact --
    equivalent to (but faster than) literally re-measuring at fine Z steps.
    """
    deps = bpy.context.evaluated_depsgraph_get()
    eo = model_obj.evaluated_get(deps)
    me = eo.to_mesh()
    max_dx = 0.0
    max_dy = 0.0
    try:
        M = eo.matrix_world
        for v in me.vertices:
            wc = M @ v.co
            if z_min <= wc.z <= z_max:
                max_dx = max(max_dx, abs(wc.x - center_x))
                max_dy = max(max_dy, abs(wc.y - center_y))
    finally:
        eo.to_mesh_clear()
    return max_dx, max_dy

def apply_universal_cylindrical_trim(final_jig, jig_min, jig_max, model_obj, scan_z_min, scan_z_max):
    """
    Subtracts a hollow disc (100mm-radius outer cylinder, unchanged) with a
    rectangular protected zone punched out of its middle -- instead of a round
    22mm bore -- from the jig, centered on the jig's X/Y center, spanning its
    full Z range + 2mm. The inner rectangle's half-widths are sized from the
    model's own geometry (max X/Y vertex distance from center within
    [scan_z_min, scan_z_max]) plus a 2mm safety margin, floored at 11mm
    (radius, i.e. the 22mm bore's diameter) so that region -- which fully
    contains the actual cavity impression with margin to spare -- is
    protected from removal, and only the area between it and the 100mm
    outer boundary gets trimmed away.
    Returns (cx, cy, half_x, half_y) so downstream pieces can share the same
    center axis and match the same rectangle the trim left behind.
    """
    cx = (jig_min[0] + jig_max[0]) / 2.0
    cy = (jig_min[1] + jig_max[1]) / 2.0
    cz = (jig_min[2] + jig_max[2]) / 2.0
    tube_height = (jig_max[2] - jig_min[2]) + 2.0

    max_dx, max_dy = measure_model_xy_extent(model_obj, cx, cy, scan_z_min, scan_z_max)
    margin = 2.0  # safety buffer on the measured extent so the trim can't shave into the cavity wall
    half_x = max(11.0, max_dx + margin)
    half_y = max(11.0, max_dy + margin)
    print(f"   -> Universal trim protected rect: half_x={half_x:.2f}mm half_y={half_y:.2f}mm "
          f"(model max_dx={max_dx:.2f} max_dy={max_dy:.2f} in z=[{scan_z_min:.2f},{scan_z_max:.2f}])")

    outer = create_cylinder("UTrim_Outer", radius=100.0, depth=tube_height, location=(cx, cy, cz))
    inner = create_box(
        "UTrim_Inner",
        (cx - half_x, cy - half_y, cz - (tube_height + 2.0) / 2.0),
        (cx + half_x, cy + half_y, cz + (tube_height + 2.0) / 2.0)
    )
    tube = apply_boolean(outer, inner, 'DIFFERENCE')  # disc with a rectangular hole

    apply_boolean(final_jig, tube, 'DIFFERENCE')
    return cx, cy, half_x, half_y

def build_twist_lock_connector(center_x, center_y, base_z, half_x, half_y, outward_sign=1.0,
                                boss_height=1.2, locker_dia=13.0):
    """
    Rebuilds the OpenSCAD twist-lock connector (body_a - body_b) in Blender.
    OpenSCAD local z=0 maps to world base_z; the body extends toward
    outward_sign * Z from there (away from the jig, mirrored via outward_sign
    when the flat face is on the -Z/bottom side instead of +Z/top), sharing
    the (center_x, center_y) axis of the cylindrical trim. body_a's outer
    edge is a box (half_x/half_y) matching the trim's protected rectangle,
    instead of a fixed r11 circle. body_a's thickness (boss_height) and its
    through-hole diameter (locker_dia) are configurable; the anti-rotation
    notch itself (body_b's keyed peg shape) is untouched -- only its Z-span
    is re-fit to whatever boss_height is set to, so it still fully cuts
    through body_a.
    """
    def world_z(local_z):
        return base_z + outward_sign * local_z

    locker_radius = locker_dia / 2.0
    body_b_center_local = boss_height / 2.0
    body_b_depth = boss_height + 2.0  # 1mm overshoot on each side, whatever boss_height is

    # body_a: washer, box(half_x, half_y) outer / locker_radius inner, local z 0..boss_height
    a_z_lo, a_z_hi = sorted((world_z(0.0), world_z(boss_height)))
    a_outer = create_box(
        "BodyA_Outer",
        (center_x - half_x, center_y - half_y, a_z_lo),
        (center_x + half_x, center_y + half_y, a_z_hi)
    )
    a_inner = create_cylinder("BodyA_Inner", radius=locker_radius, depth=boss_height + 4.0,
                               location=(center_x, center_y, world_z(body_b_center_local)))
    body_a = apply_boolean(a_outer, a_inner, 'DIFFERENCE')

    # body_b: keyed peg (anti-rotation notch, unchanged shape), re-spanned in Z
    body_b = create_cylinder("BodyB", radius=9.5, depth=body_b_depth,
                              location=(center_x, center_y, world_z(body_b_center_local)))

    def cut_box(target, size_x, size_y, size_z, local_center):
        bpy.ops.mesh.primitive_cube_add(size=1, location=(
            center_x + local_center[0], center_y + local_center[1], world_z(local_center[2])
        ))
        box = bpy.context.active_object
        box.scale = (size_x, size_y, size_z)
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
        return apply_boolean(target, box, 'DIFFERENCE')

    # translate([0,-23/2,-2]) cube([12,23,6])       -> local center (6, 0, body_b_center_local)
    box_z = body_b_depth + 2.0  # extra overshoot so these fully perforate body_b
    body_b = cut_box(body_b, 12, 23, box_z, (6.0, 0.0, body_b_center_local))
    # translate([-23/2,-12,-2]) cube([23,9.7,6])    -> local center (0, -7.15, body_b_center_local)
    body_b = cut_box(body_b, 23, 9.7, box_z, (0.0, -12.0 + 9.7 / 2.0, body_b_center_local))
    # translate([-23/2,2.3,-2]) cube([23,9.7,6])    -> local center (0, 7.15, body_b_center_local)
    body_b = cut_box(body_b, 23, 9.7, box_z, (0.0, 2.3 + 9.7 / 2.0, body_b_center_local))

    connector = apply_boolean(body_a, body_b, 'DIFFERENCE')
    connector.name = "Universal_Connector"
    return connector

def append_solid_box(final_jig, center_x, center_y, flat_face_z, outward_sign, half_x, half_y, height):
    """
    Unions a solid rectangular box onto the jig at flat_face_z, extending
    outward_sign * Z by `height`, thickening the jig there. half_x/half_y
    match the trim's protected rectangle so the boss's outer edge lines up
    with the shape the trim left behind. Returns the new outer flat_face_z.
    """
    new_face_z = flat_face_z + outward_sign * height
    z_lo, z_hi = sorted((flat_face_z, new_face_z))
    boss = create_box(
        "Boss_Solid",
        (center_x - half_x, center_y - half_y, z_lo),
        (center_x + half_x, center_y + half_y, z_hi)
    )
    apply_boolean(final_jig, boss, 'UNION')
    return new_face_z

def apply_universal_pin_pierce(final_jig, center_x, center_y, tip_z, outer_face_z, pin_dia=7.4):
    """
    Pierces a "pin" shape into the jig: a 60-degree (included-angle) cone whose
    tip touches tip_z exactly (the figure's own outer boundary -- it neither
    falls short of nor punches past the model), widening to pin_dia at its
    flat end, which then transitions into a same-diameter cylindrical shaft.
    The shaft's length isn't fixed -- it's whatever's needed to reach 1mm past
    outer_face_z (the jig+boss block's actual outer surface), so the cut is
    always fully clean and always fully spans the block regardless of how
    tall the boss ends up being.
    """
    pin_radius = pin_dia / 2.0
    half_angle = math.radians(30.0)  # 60-degree included angle -> 30-degree half-angle
    cone_height = pin_radius / math.tan(half_angle)
    cut_margin = 1.0  # extra length past outer_face_z for a clean cut

    direction = 1.0 if outer_face_z >= tip_z else -1.0  # which way is "outward" (tip -> surface)
    wide_z = tip_z + direction * cone_height             # cone's flat end, where the shaft begins
    cut_end_z = outer_face_z + direction * cut_margin    # 1mm past the block's actual outer face

    # Cone: tip at tip_z (radius 0), flat/wide end at wide_z (radius = pin_radius)
    low_z, high_z = min(tip_z, wide_z), max(tip_z, wide_z)
    radius1 = 0.0 if tip_z < wide_z else pin_radius  # radius at the -Z (lower) end
    radius2 = pin_radius if tip_z < wide_z else 0.0  # radius at the +Z (upper) end
    bpy.ops.mesh.primitive_cone_add(
        radius1=radius1, radius2=radius2, depth=(high_z - low_z),
        location=(center_x, center_y, (low_z + high_z) / 2.0), vertices=100
    )
    cone = bpy.context.active_object
    cone.name = "UPin_Cone"

    # Shaft: same diameter, from the cone's wide end out to cut_end_z (includes cut_margin)
    s_lo, s_hi = sorted((wide_z, cut_end_z))
    shaft = create_cylinder("UPin_Shaft", radius=pin_radius, depth=(s_hi - s_lo),
                             location=(center_x, center_y, (s_lo + s_hi) / 2.0))

    pin_tool = apply_boolean(cone, shaft, 'UNION')
    apply_boolean(final_jig, pin_tool, 'DIFFERENCE')

    return cone_height

# ==========================================
# CORE 3D SPATIAL JIG FUNCTION
# ==========================================
def generate_jig_in_place(
    raw_model,
    master_min,
    master_max,
    overlap,
    bottom_thickness=1.0,
    inflation=0.4,
    target_tris=50000,
    direction='+Z',
    u_minus_pin_dia=7.4,
    u_plus_locker_dia=13.0,
    u_plus_boss_height=1.2,
    u_minus_boss_height=None,
):
    print(f"\n[FUNC] Generating low-profile {direction} Jig...")
    
    # 1. Duplicate working model
    working_model = raw_model.copy()
    working_model.data = raw_model.data.copy()
    working_model.name = f"Working_Cutter_{direction}"
    bpy.context.collection.objects.link(working_model)
    bpy.context.view_layer.objects.active = working_model

    # 2. Get absolute model bounds
    bbox = [working_model.matrix_world @ mathutils.Vector(b) for b in working_model.bound_box]
    mod_min = (min(b.x for b in bbox), min(b.y for b in bbox), min(b.z for b in bbox))
    mod_max = (max(b.x for b in bbox), max(b.y for b in bbox), max(b.z for b in bbox))

    # 3. SPATIAL MAPPING LOGIC (Updated for Low-Profile Thickness)
    clearance = 5.0 
    inf = 1000.0    
    # 73, 145, 50
    if direction == '+Z': # Jig on Bottom
        jig_min = (master_min[0], master_min[1], mod_min[2] - bottom_thickness)
        jig_max = (master_max[0], master_max[1], mod_min[2] + overlap)
        cut_min = (-inf, -inf, mod_min[2] + overlap + clearance)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 0, 1))
        
    elif direction == '-Z': # Jig on Top
        jig_min = (master_min[0], master_min[1], mod_max[2] - overlap)
        jig_max = (master_max[0], master_max[1], mod_max[2] + bottom_thickness)
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, inf, mod_max[2] - overlap - clearance)
        sweep_vec = mathutils.Vector((0, 0, -1))

    elif direction == '+U': # Universal Jig (copy of +Z, Jig on Bottom)
        jig_min = (master_min[0], master_min[1], mod_min[2] - bottom_thickness)
        jig_max = (master_max[0], master_max[1], mod_min[2] + overlap)
        cut_min = (-inf, -inf, mod_min[2] + overlap + clearance)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 0, 1))

    elif direction == '-U': # Universal Jig (copy of -Z, Jig on Top)
        jig_min = (master_min[0], master_min[1], mod_max[2] - overlap)
        jig_max = (master_max[0], master_max[1], mod_max[2] + bottom_thickness)
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, inf, mod_max[2] - overlap - clearance)
        sweep_vec = mathutils.Vector((0, 0, -1))

    elif direction == '+X': # Jig on Left
        jig_min = (mod_min[0] - bottom_thickness, master_min[1], master_min[2])
        jig_max = (mod_min[0] + overlap, master_max[1], master_max[2])
        cut_min = (mod_min[0] + overlap + clearance, -inf, -inf)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((1, 0, 0))
        
    elif direction == '-X': # Jig on Right
        jig_min = (mod_max[0] - overlap, master_min[1], master_min[2])
        jig_max = (mod_max[0] + bottom_thickness, master_max[1], master_max[2])
        cut_min = (-inf, -inf, -inf)
        cut_max = (mod_max[0] - overlap - clearance, inf, inf)
        sweep_vec = mathutils.Vector((-1, 0, 0))
        
    elif direction == '+Y': # Jig on Front
        jig_min = (master_min[0], mod_min[1] - bottom_thickness, master_min[2])
        jig_max = (master_max[0], mod_min[1] + overlap, master_max[2])
        cut_min = (-inf, mod_min[1] + overlap + clearance, -inf)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 1, 0))
        
    elif direction == '-Y': # Jig on Back
        jig_min = (master_min[0], mod_max[1] - overlap, master_min[2])
        jig_max = (master_max[0], mod_max[1] + bottom_thickness, master_max[2])
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, mod_max[1] - overlap - clearance, inf)
        sweep_vec = mathutils.Vector((0, -1, 0))

    # 4. Trim Excessive Model
    trim_cutter = create_box(f"Trim_{direction}", cut_min, cut_max)
    bpy.context.view_layer.objects.active = working_model
    trim_mod = working_model.modifiers.new(type="BOOLEAN", name="Trim")
    trim_mod.object = trim_cutter
    trim_mod.operation = 'DIFFERENCE'
    trim_mod.solver = 'EXACT'
    bpy.ops.object.modifier_apply(modifier=trim_mod.name)
    bpy.data.objects.remove(trim_cutter, do_unlink=True)

    # 5. Simplify & Inflate
    working_model.data.calc_loop_triangles()
    if len(working_model.data.loop_triangles) > target_tris:
        decimate_mod = working_model.modifiers.new(type="DECIMATE", name="Optimize")
        decimate_mod.decimate_type = 'COLLAPSE'
        decimate_mod.ratio = target_tris / len(working_model.data.loop_triangles)
        bpy.ops.object.modifier_apply(modifier=decimate_mod.name)

    bpy.ops.object.editmode_toggle()
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.normals_make_consistent(inside=False)
    bpy.ops.object.editmode_toggle()

    disp_mod = working_model.modifiers.new(type="DISPLACE", name="Inflate")
    disp_mod.strength = inflation
    disp_mod.mid_level = 0.0
    bpy.ops.object.modifier_apply(modifier=disp_mod.name)

    # 6. Create the specific Jig Box side
    final_jig = create_box(f"Jig_{direction}", jig_min, jig_max)

    # 7. Sweep the Master Cutter
    move_distance = overlap + 2.0 
    step_size = 0.5
    steps = int(math.ceil(move_distance / step_size))

    bpy.ops.object.select_all(action='DESELECT')
    cutter_parts = []
    for i in range(steps + 1):
        dup = working_model.copy()
        dup.data = working_model.data.copy()
        bpy.context.collection.objects.link(dup)
        
        translation = sweep_vec * (i * step_size)
        dup.location.x += translation.x
        dup.location.y += translation.y
        dup.location.z += translation.z
        cutter_parts.append(dup)

    for part in cutter_parts: part.select_set(True)
    bpy.context.view_layer.objects.active = cutter_parts[0]
    bpy.ops.object.join()
    master_cutter = bpy.context.active_object

    remesh_mod = master_cutter.modifiers.new(type='REMESH', name='Fuse_Slices')
    remesh_mod.mode = 'VOXEL'
    remesh_mod.voxel_size = 0.5
    bpy.ops.object.modifier_apply(modifier=remesh_mod.name)

    # 8. Punch the cavity
    bpy.ops.object.select_all(action='DESELECT')
    bpy.context.view_layer.objects.active = final_jig

    final_cut = final_jig.modifiers.new(type="BOOLEAN", name="Jig_Cut")
    final_cut.object = master_cutter
    final_cut.operation = 'DIFFERENCE'
    final_cut.solver = 'EXACT' 
    final_cut.double_threshold = 0.0001
    bpy.ops.object.modifier_apply(modifier=final_cut.name)

    # 8.5 UNIVERSAL JIG (+U / -U) POST-PROCESS
    if direction in ('+U', '-U'):
        print(f"   -> Applying Universal Jig post-process ({direction})...")
        # Scan the model over exactly the slice that becomes the cavity impression
        # (from this side's extreme point, `overlap` deep) to size the trim's outer
        # rectangle so it can't cut into the cavity's walls.
        if direction == '+U':
            scan_z_min, scan_z_max = mod_min[2], mod_min[2] + overlap
        else:  # '-U'
            scan_z_min, scan_z_max = mod_max[2] - overlap, mod_max[2]
        cx, cy, half_x, half_y = apply_universal_cylindrical_trim(final_jig, jig_min, jig_max, raw_model, scan_z_min, scan_z_max)
        if direction == '+U':
            # Flat face is at jig_min.z (bottom); connector extends away from the jig, toward -Z.
            connector = build_twist_lock_connector(cx, cy, base_z=jig_min[2], half_x=half_x, half_y=half_y,
                                                    outward_sign=-1.0, boss_height=u_plus_boss_height,
                                                    locker_dia=u_plus_locker_dia)
            apply_boolean(final_jig, connector, 'UNION')
        elif direction == '-U':
            # Flat face is at jig_max.z (top); outward is +Z. Boss height defaults to a
            # nominal cone+3mm reference (just for sizing), unless overridden.
            pin_radius = u_minus_pin_dia / 2.0
            pin_cone_height = pin_radius / math.tan(math.radians(30.0))
            boss_height_minus = u_minus_boss_height if u_minus_boss_height is not None \
                else (pin_cone_height + 3.0)
            new_face_z = append_solid_box(final_jig, cx, cy, flat_face_z=jig_max[2],
                                           outward_sign=1.0, half_x=half_x, half_y=half_y,
                                           height=boss_height_minus)
            # Tip touches the figure's own outer boundary (mod_max.z) exactly -- neither short
            # of nor past the model. The cylindrical shaft's length isn't fixed: it extends
            # from the cone's flat end all the way to 1mm past the block's actual outer face
            # (new_face_z), so the cut always fully spans the boss regardless of its height.
            apply_universal_pin_pierce(final_jig, cx, cy, tip_z=mod_max[2], outer_face_z=new_face_z,
                                        pin_dia=u_minus_pin_dia)

    # 9. Cleanup
    bpy.data.objects.remove(working_model, do_unlink=True)
    bpy.data.objects.remove(master_cutter, do_unlink=True)

    return final_jig

# ==========================================
# FULL 6-SIDED EXECUTION PIPELINE
# ==========================================
if __name__ == "__main__":
    import argparse
    import sys
    # Handle Blender arg passing (if run inside blender)
    argv = sys.argv[1:]
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]

    parser = argparse.ArgumentParser()
    parser.add_argument("--input_glb", type=str, required=True)
    parser.add_argument("--output_dir", type=str, required=True)
    parser.add_argument("--model_name_seed", type=str, default="model")
    parser.add_argument("--slot_center", type=float, nargs=3, required=True)
    parser.add_argument("--slot_size", type=float, nargs=2, required=True)
    parser.add_argument("--jigs_requested", type=str, default="")
    parser.add_argument("--overlap_x", type=float, default=3.0)
    parser.add_argument("--overlap_y", type=float, default=5.0)
    parser.add_argument("--overlap_z", type=float, default=5.0)
    parser.add_argument("--inflation_margin", type=float, default=0.4)
    parser.add_argument("--grid_height", type=float, default=50.0)
    parser.add_argument("--u_minus_pin_dia_mm", type=float, default=7.4)
    parser.add_argument("--u_plus_locker_dia_mm", type=float, default=13.0)
    parser.add_argument("--u_plus_boss_height_mm", type=float, default=1.2)
    parser.add_argument("--u_minus_boss_height_mm", type=float, default=None)

    args = parser.parse_args(argv)

    GLB_INPUT_PATH = args.input_glb
    os.makedirs(args.output_dir, exist_ok=True)
    BLEND_OUTPUT_PATH = os.path.join(args.output_dir, f"{args.model_name_seed}_jigs.blend")
    
    print("[INIT] Cleaning up scene...")
    bpy.ops.object.select_all(action='DESELECT')
    for obj in bpy.context.scene.objects:
        if obj.type == 'MESH': obj.select_set(True)
    bpy.ops.object.delete()

    # 2. Import and Pre-Scale
    bpy.ops.import_scene.gltf(filepath=GLB_INPUT_PATH)
    raw_model = bpy.context.selected_objects[0]
    raw_model.name = "Original_Model"
    bpy.context.view_layer.objects.active = raw_model
    
    HEIGHT = args.slot_size[1] - 2 # Y in render script is Z here.
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    z_height = max(b.z for b in bbox) - min(b.z for b in bbox)
    scale_factor = HEIGHT / z_height
    raw_model.scale = (scale_factor, scale_factor, scale_factor)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    # 3. Center model at slot_center
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    cx = (max(b.x for b in bbox) + min(b.x for b in bbox)) / 2.0
    cy = (max(b.y for b in bbox) + min(b.y for b in bbox)) / 2.0
    cz = (max(b.z for b in bbox) + min(b.z for b in bbox)) / 2.0
    raw_model.location = (args.slot_center[0] - cx, args.slot_center[1] - cy, args.slot_center[2] - cz)
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)

    print("[PROCESS] Calculating spatial constraints...")
    # 4. Process Control Variables
    MASTER_X, MASTER_Y, MASTER_Z = args.slot_size[0], args.grid_height, args.slot_size[1] # X, Y in render script is X and Z here. Slot Height is Y
    # Card
    # 73, 145, 50
    master_min = (args.slot_center[0] - MASTER_X/2, args.slot_center[1] - MASTER_Y/2, args.slot_center[2] - MASTER_Z/2)
    master_max = (args.slot_center[0] + MASTER_X/2, args.slot_center[1] + MASTER_Y/2, args.slot_center[2] + MASTER_Z/2)

    OVERLAP_Z = args.overlap_z 
    BOTTOM_THICKNESS = 1.0 # The fixed backing thickness for the UV print bed

    # 5. Generate specified jigs
    if args.jigs_requested:
        directions = [d.strip() for d in args.jigs_requested.split(",") if d.strip()]
    else:
        directions = ['+Z', '-Z', '+X', '-X', '+Y', '-Y']

    print(f"[PROCESS] Creating {len(directions)} jigs: {directions}")
    for d in directions:
        print(f"   -> Starting generation for {d}...")
        final_jig = generate_jig_in_place(
            raw_model=raw_model,
            master_min=master_min,
            master_max=master_max,
            overlap=OVERLAP_Z,
            bottom_thickness=BOTTOM_THICKNESS,
            inflation=args.inflation_margin,
            direction=d,
            u_minus_pin_dia=args.u_minus_pin_dia_mm,
            u_plus_locker_dia=args.u_plus_locker_dia_mm,
            u_plus_boss_height=args.u_plus_boss_height_mm,
            u_minus_boss_height=args.u_minus_boss_height_mm,
        )
        
        # Export each individual jig STL
        bpy.ops.object.select_all(action='DESELECT')
        final_jig.select_set(True)
        bpy.context.view_layer.objects.active = final_jig
        stl_path = os.path.join(args.output_dir, f"{args.model_name_seed}_jig_{d}.stl")
        
        try:
            bpy.ops.export_mesh.stl(filepath=stl_path, use_selection=True)
        except Exception as e:
            print(f"      [WARN] Standard STL export failed: {e}. Falling back to binary writer...")
            _write_binary_stl_all(stl_path, final_jig)
        print(f"   -> Completed generation for {d}")

    print("[PROCESS] Exporting RAW Base Figure...")
    # 6. Export the RAW Base Figure
    bpy.ops.object.select_all(action='DESELECT')
    raw_model.select_set(True)
    bpy.context.view_layer.objects.active = raw_model
    figure_stl_path = os.path.join(args.output_dir, f"{args.model_name_seed}_figure.stl")
    try:
        bpy.ops.export_mesh.stl(filepath=figure_stl_path, use_selection=True)
    except Exception as e:
        print(f"Standard STL export for figure failed: {e}. Falling back to binary writer...")
        _write_binary_stl_all(figure_stl_path, raw_model)
    print(f"[OK] Base Figure STL Exported: {figure_stl_path}")
    
    print("[PROCESS] Saving Combined Blend File...")
    # 7. Save Combined Blend
    bpy.context.view_layer.update()
    bpy.ops.wm.save_as_mainfile(filepath=BLEND_OUTPUT_PATH)

    print("[PROCESS] Exporting Jigs Metadata...")
    import json
    meta_path = os.path.join(args.output_dir, f"{args.model_name_seed}_jigs_meta.json")
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    meta_data = {
        "master_size": {"x": MASTER_X, "y": MASTER_Y, "z": MASTER_Z},
        "figure_bounds": {
            "min_x": min(b.x for b in bbox), "min_y": min(b.y for b in bbox), "min_z": min(b.z for b in bbox),
            "max_x": max(b.x for b in bbox), "max_y": max(b.y for b in bbox), "max_z": max(b.z for b in bbox)
        }
    }
    with open(meta_path, 'w') as f:
        json.dump(meta_data, f, indent=4)

    print(f"[SUCCESS] Low-Profile Production Jig Generation Complete! Exiting.")
    import sys
    sys.exit(0)