import bpy
import bmesh
import mathutils
import math
import os
import struct
from mathutils import Vector

_GEOM_TYPES = {"MESH", "CURVE", "FONT", "SURFACE"}  # what we want in STL

def _iter_world_tris_any(obj):
    """Yield world-space triangles (v0,v1,v2) for any supported object via evaluated mesh."""
    deps = bpy.context.evaluated_depsgraph_get()
    eo = obj.evaluated_get(deps)
    me = eo.to_mesh()
    try:
        if not me:
            return
        me.calc_loop_triangles()
        verts = me.vertices
        M = eo.matrix_world
        for tri in me.loop_triangles:
            v0 = M @ verts[tri.vertices[0]].co
            v1 = M @ verts[tri.vertices[1]].co
            v2 = M @ verts[tri.vertices[2]].co
            yield (v0, v1, v2)
    finally:
        eo.to_mesh_clear()

def _write_binary_stl_all(path_stl: str, target_obj):
    """Addon-free writer that exports a specific object."""
    # Count triangles
    tri_count = 0
    for _ in _iter_world_tris_any(target_obj):
        tri_count += 1

    with open(path_stl, "wb") as f:
        f.write(b"Generated by Blender script".ljust(80, b"\0"))
        f.write(struct.pack("<I", tri_count))
        for v0, v1, v2 in _iter_world_tris_any(target_obj):
            n = (v1 - v0).cross(v2 - v0)
            ln = n.length
            if ln > 1e-20: n /= ln
            else:          n = Vector((0.0, 0.0, 0.0))
            f.write(struct.pack(
                "<12fH",
                float(n.x), float(n.y), float(n.z),
                float(v0.x), float(v0.y), float(v0.z),
                float(v1.x), float(v1.y), float(v1.z),
                float(v2.x), float(v2.y), float(v2.z),
                0
            ))
    print(f"[OK] Fallback STL Exported: {path_stl}")

# ==========================================
# HELPER: CREATE BOX FROM BOUNDS
# ==========================================
def create_box(name, min_bounds, max_bounds):
    """Creates a cube perfectly bounded by two 3D coordinate vectors."""
    dx = max_bounds[0] - min_bounds[0]
    dy = max_bounds[1] - min_bounds[1]
    dz = max_bounds[2] - min_bounds[2]
    
    cx = (max_bounds[0] + min_bounds[0]) / 2.0
    cy = (max_bounds[1] + min_bounds[1]) / 2.0
    cz = (max_bounds[2] + min_bounds[2]) / 2.0
    
    bpy.ops.mesh.primitive_cube_add(size=1)
    box = bpy.context.active_object
    box.name = name
    box.scale = (dx, dy, dz)
    box.location = (cx, cy, cz)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    return box

# ==========================================
# HELPERS: CYLINDER PRIMITIVE + BOOLEAN OP
# ==========================================
def create_cylinder(name, radius, depth, location=(0.0, 0.0, 0.0), verts=100):
    """Creates a Z-axis cylinder of given radius/depth, centered at location."""
    bpy.ops.mesh.primitive_cylinder_add(
        radius=radius, depth=depth, location=location, vertices=verts
    )
    cyl = bpy.context.active_object
    cyl.name = name
    return cyl

def apply_boolean(target, cutter, operation='DIFFERENCE'):
    """Applies a boolean modifier to target using cutter, applies it, deletes cutter."""
    mod = target.modifiers.new(type="BOOLEAN", name=f"Bool_{operation}")
    mod.object = cutter
    mod.operation = operation
    mod.solver = 'EXACT'
    bpy.context.view_layer.objects.active = target
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(cutter, do_unlink=True)
    return target

# ==========================================
# UNIVERSAL JIG (+U / -U) POST-PROCESS
# ==========================================
def apply_universal_cylindrical_trim(final_jig, jig_min, jig_max):
    """
    Subtracts a hollow cylinder (ID 22mm / OD 200mm) from the jig, centered on
    the jig's X/Y center, spanning its full Z range + 2mm. Trims the jig's
    sides into a cylindrical form.
    Returns (cx, cy) so downstream pieces can share the same center axis.
    """
    cx = (jig_min[0] + jig_max[0]) / 2.0
    cy = (jig_min[1] + jig_max[1]) / 2.0
    cz = (jig_min[2] + jig_max[2]) / 2.0
    tube_height = (jig_max[2] - jig_min[2]) + 2.0

    outer = create_cylinder("UTrim_Outer", radius=100.0, depth=tube_height, location=(cx, cy, cz))
    inner = create_cylinder("UTrim_Inner", radius=11.0, depth=tube_height + 2.0, location=(cx, cy, cz))
    tube = apply_boolean(outer, inner, 'DIFFERENCE')  # hollow cylinder / annulus

    apply_boolean(final_jig, tube, 'DIFFERENCE')
    return cx, cy

def build_twist_lock_connector(center_x, center_y, base_z):
    """
    Rebuilds the OpenSCAD twist-lock connector (body_a - body_b) in Blender.
    OpenSCAD local z=0 maps to world base_z; the body extends in +Z from there
    (away from the jig), sharing the (center_x, center_y) axis of the cylindrical trim.
    """
    def world_z(local_z):
        return base_z + local_z

    # body_a: washer, r11 outer / r6.5 inner, local z 0..2
    a_outer = create_cylinder("BodyA_Outer", radius=11.0, depth=2.0,
                               location=(center_x, center_y, world_z(1.0)))
    a_inner = create_cylinder("BodyA_Inner", radius=6.5, depth=6.0,
                               location=(center_x, center_y, world_z(1.0)))
    body_a = apply_boolean(a_outer, a_inner, 'DIFFERENCE')

    # body_b: keyed peg, r9.5, local z -1..3, minus 3 boxes
    body_b = create_cylinder("BodyB", radius=9.5, depth=4.0,
                              location=(center_x, center_y, world_z(1.0)))

    def cut_box(target, size_x, size_y, size_z, local_center):
        bpy.ops.mesh.primitive_cube_add(size=1, location=(
            center_x + local_center[0], center_y + local_center[1], world_z(local_center[2])
        ))
        box = bpy.context.active_object
        box.scale = (size_x, size_y, size_z)
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
        return apply_boolean(target, box, 'DIFFERENCE')

    # translate([0,-23/2,-2]) cube([12,23,6])       -> local center (6, 0, 1)
    body_b = cut_box(body_b, 12, 23, 6, (6.0, 0.0, 1.0))
    # translate([-23/2,-12,-2]) cube([23,9.7,6])    -> local center (0, -7.15, 1)
    body_b = cut_box(body_b, 23, 9.7, 6, (0.0, -12.0 + 9.7 / 2.0, 1.0))
    # translate([-23/2,2.3,-2]) cube([23,9.7,6])    -> local center (0, 7.15, 1)
    body_b = cut_box(body_b, 23, 9.7, 6, (0.0, 2.3 + 9.7 / 2.0, 1.0))

    connector = apply_boolean(body_a, body_b, 'DIFFERENCE')
    connector.name = "Universal_Connector"
    return connector

def apply_universal_cone_pierce(final_jig, jig_min, jig_max, center_x, center_y):
    """
    Pierces a 60-degree (included-angle) centering cone into the jig, starting
    3mm inside the -Z flat face and boring toward +Z. Base diameter is 24mm
    (> the 22mm bore); height is derived from the 60-degree cone angle so the
    cone tapers to a point.
    """
    cone_diameter = 24.0  # > 22mm bore
    cone_radius = cone_diameter / 2.0
    half_angle = math.radians(30.0)  # 60-degree included angle -> 30-degree half-angle
    cone_height = cone_radius / math.tan(half_angle)

    base_z = jig_min[2] + 3.0
    apex_z = base_z + cone_height

    bpy.ops.mesh.primitive_cone_add(
        radius1=cone_radius, radius2=0.0, depth=cone_height,
        location=(center_x, center_y, (base_z + apex_z) / 2.0), vertices=100
    )
    cone = bpy.context.active_object
    cone.name = "UCone_Cutter"
    apply_boolean(final_jig, cone, 'DIFFERENCE')

# ==========================================
# CORE 3D SPATIAL JIG FUNCTION
# ==========================================
def generate_jig_in_place(
    raw_model, 
    master_min, 
    master_max, 
    overlap, 
    bottom_thickness=1.0, 
    inflation=0.4, 
    target_tris=50000, 
    direction='+Z'
):
    print(f"\n[FUNC] Generating low-profile {direction} Jig...")
    
    # 1. Duplicate working model
    working_model = raw_model.copy()
    working_model.data = raw_model.data.copy()
    working_model.name = f"Working_Cutter_{direction}"
    bpy.context.collection.objects.link(working_model)
    bpy.context.view_layer.objects.active = working_model

    # 2. Get absolute model bounds
    bbox = [working_model.matrix_world @ mathutils.Vector(b) for b in working_model.bound_box]
    mod_min = (min(b.x for b in bbox), min(b.y for b in bbox), min(b.z for b in bbox))
    mod_max = (max(b.x for b in bbox), max(b.y for b in bbox), max(b.z for b in bbox))

    # 3. SPATIAL MAPPING LOGIC (Updated for Low-Profile Thickness)
    clearance = 5.0 
    inf = 1000.0    
    # 73, 145, 50
    if direction == '+Z': # Jig on Bottom
        jig_min = (master_min[0], master_min[1], mod_min[2] - bottom_thickness)
        jig_max = (master_max[0], master_max[1], mod_min[2] + overlap)
        cut_min = (-inf, -inf, mod_min[2] + overlap + clearance)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 0, 1))
        
    elif direction == '-Z': # Jig on Top
        jig_min = (master_min[0], master_min[1], mod_max[2] - overlap)
        jig_max = (master_max[0], master_max[1], mod_max[2] + bottom_thickness)
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, inf, mod_max[2] - overlap - clearance)
        sweep_vec = mathutils.Vector((0, 0, -1))

    elif direction == '+U': # Universal Jig (copy of +Z, Jig on Bottom)
        jig_min = (master_min[0], master_min[1], mod_min[2] - bottom_thickness)
        jig_max = (master_max[0], master_max[1], mod_min[2] + overlap)
        cut_min = (-inf, -inf, mod_min[2] + overlap + clearance)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 0, 1))

    elif direction == '-U': # Universal Jig (copy of -Z, Jig on Top)
        jig_min = (master_min[0], master_min[1], mod_max[2] - overlap)
        jig_max = (master_max[0], master_max[1], mod_max[2] + bottom_thickness)
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, inf, mod_max[2] - overlap - clearance)
        sweep_vec = mathutils.Vector((0, 0, -1))

    elif direction == '+X': # Jig on Left
        jig_min = (mod_min[0] - bottom_thickness, master_min[1], master_min[2])
        jig_max = (mod_min[0] + overlap, master_max[1], master_max[2])
        cut_min = (mod_min[0] + overlap + clearance, -inf, -inf)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((1, 0, 0))
        
    elif direction == '-X': # Jig on Right
        jig_min = (mod_max[0] - overlap, master_min[1], master_min[2])
        jig_max = (mod_max[0] + bottom_thickness, master_max[1], master_max[2])
        cut_min = (-inf, -inf, -inf)
        cut_max = (mod_max[0] - overlap - clearance, inf, inf)
        sweep_vec = mathutils.Vector((-1, 0, 0))
        
    elif direction == '+Y': # Jig on Front
        jig_min = (master_min[0], mod_min[1] - bottom_thickness, master_min[2])
        jig_max = (master_max[0], mod_min[1] + overlap, master_max[2])
        cut_min = (-inf, mod_min[1] + overlap + clearance, -inf)
        cut_max = (inf, inf, inf)
        sweep_vec = mathutils.Vector((0, 1, 0))
        
    elif direction == '-Y': # Jig on Back
        jig_min = (master_min[0], mod_max[1] - overlap, master_min[2])
        jig_max = (master_max[0], mod_max[1] + bottom_thickness, master_max[2])
        cut_min = (-inf, -inf, -inf)
        cut_max = (inf, mod_max[1] - overlap - clearance, inf)
        sweep_vec = mathutils.Vector((0, -1, 0))

    # 4. Trim Excessive Model
    trim_cutter = create_box(f"Trim_{direction}", cut_min, cut_max)
    bpy.context.view_layer.objects.active = working_model
    trim_mod = working_model.modifiers.new(type="BOOLEAN", name="Trim")
    trim_mod.object = trim_cutter
    trim_mod.operation = 'DIFFERENCE'
    trim_mod.solver = 'EXACT'
    bpy.ops.object.modifier_apply(modifier=trim_mod.name)
    bpy.data.objects.remove(trim_cutter, do_unlink=True)

    # 5. Simplify & Inflate
    working_model.data.calc_loop_triangles()
    if len(working_model.data.loop_triangles) > target_tris:
        decimate_mod = working_model.modifiers.new(type="DECIMATE", name="Optimize")
        decimate_mod.decimate_type = 'COLLAPSE'
        decimate_mod.ratio = target_tris / len(working_model.data.loop_triangles)
        bpy.ops.object.modifier_apply(modifier=decimate_mod.name)

    bpy.ops.object.editmode_toggle()
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.mesh.normals_make_consistent(inside=False)
    bpy.ops.object.editmode_toggle()

    disp_mod = working_model.modifiers.new(type="DISPLACE", name="Inflate")
    disp_mod.strength = inflation
    disp_mod.mid_level = 0.0
    bpy.ops.object.modifier_apply(modifier=disp_mod.name)

    # 6. Create the specific Jig Box side
    final_jig = create_box(f"Jig_{direction}", jig_min, jig_max)

    # 7. Sweep the Master Cutter
    move_distance = overlap + 2.0 
    step_size = 0.5
    steps = int(math.ceil(move_distance / step_size))

    bpy.ops.object.select_all(action='DESELECT')
    cutter_parts = []
    for i in range(steps + 1):
        dup = working_model.copy()
        dup.data = working_model.data.copy()
        bpy.context.collection.objects.link(dup)
        
        translation = sweep_vec * (i * step_size)
        dup.location.x += translation.x
        dup.location.y += translation.y
        dup.location.z += translation.z
        cutter_parts.append(dup)

    for part in cutter_parts: part.select_set(True)
    bpy.context.view_layer.objects.active = cutter_parts[0]
    bpy.ops.object.join()
    master_cutter = bpy.context.active_object

    remesh_mod = master_cutter.modifiers.new(type='REMESH', name='Fuse_Slices')
    remesh_mod.mode = 'VOXEL'
    remesh_mod.voxel_size = 0.5
    bpy.ops.object.modifier_apply(modifier=remesh_mod.name)

    # 8. Punch the cavity
    bpy.ops.object.select_all(action='DESELECT')
    bpy.context.view_layer.objects.active = final_jig

    final_cut = final_jig.modifiers.new(type="BOOLEAN", name="Jig_Cut")
    final_cut.object = master_cutter
    final_cut.operation = 'DIFFERENCE'
    final_cut.solver = 'EXACT' 
    final_cut.double_threshold = 0.0001
    bpy.ops.object.modifier_apply(modifier=final_cut.name)

    # 8.5 UNIVERSAL JIG (+U / -U) POST-PROCESS
    if direction in ('+U', '-U'):
        print(f"   -> Applying Universal Jig post-process ({direction})...")
        cx, cy = apply_universal_cylindrical_trim(final_jig, jig_min, jig_max)
        if direction == '-U':
            connector = build_twist_lock_connector(cx, cy, base_z=jig_max[2])
            apply_boolean(final_jig, connector, 'UNION')
        elif direction == '+U':
            apply_universal_cone_pierce(final_jig, jig_min, jig_max, cx, cy)

    # 9. Cleanup
    bpy.data.objects.remove(working_model, do_unlink=True)
    bpy.data.objects.remove(master_cutter, do_unlink=True)

    return final_jig

# ==========================================
# FULL 6-SIDED EXECUTION PIPELINE
# ==========================================
if __name__ == "__main__":
    import argparse
    import sys
    # Handle Blender arg passing (if run inside blender)
    argv = sys.argv[1:]
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]

    parser = argparse.ArgumentParser()
    parser.add_argument("--input_glb", type=str, required=True)
    parser.add_argument("--output_dir", type=str, required=True)
    parser.add_argument("--model_name_seed", type=str, default="model")
    parser.add_argument("--slot_center", type=float, nargs=3, required=True)
    parser.add_argument("--slot_size", type=float, nargs=2, required=True)
    parser.add_argument("--jigs_requested", type=str, default="")
    parser.add_argument("--overlap_x", type=float, default=3.0)
    parser.add_argument("--overlap_y", type=float, default=5.0)
    parser.add_argument("--overlap_z", type=float, default=5.0)
    parser.add_argument("--inflation_margin", type=float, default=0.4)
    parser.add_argument("--grid_height", type=float, default=50.0)

    args = parser.parse_args(argv)

    GLB_INPUT_PATH = args.input_glb
    os.makedirs(args.output_dir, exist_ok=True)
    BLEND_OUTPUT_PATH = os.path.join(args.output_dir, f"{args.model_name_seed}_jigs.blend")
    
    print("[INIT] Cleaning up scene...")
    bpy.ops.object.select_all(action='DESELECT')
    for obj in bpy.context.scene.objects:
        if obj.type == 'MESH': obj.select_set(True)
    bpy.ops.object.delete()

    # 2. Import and Pre-Scale
    bpy.ops.import_scene.gltf(filepath=GLB_INPUT_PATH)
    raw_model = bpy.context.selected_objects[0]
    raw_model.name = "Original_Model"
    bpy.context.view_layer.objects.active = raw_model
    
    HEIGHT = args.slot_size[1] - 2 # Y in render script is Z here.
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    z_height = max(b.z for b in bbox) - min(b.z for b in bbox)
    scale_factor = HEIGHT / z_height
    raw_model.scale = (scale_factor, scale_factor, scale_factor)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    # 3. Center model at slot_center
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    cx = (max(b.x for b in bbox) + min(b.x for b in bbox)) / 2.0
    cy = (max(b.y for b in bbox) + min(b.y for b in bbox)) / 2.0
    cz = (max(b.z for b in bbox) + min(b.z for b in bbox)) / 2.0
    raw_model.location = (args.slot_center[0] - cx, args.slot_center[1] - cy, args.slot_center[2] - cz)
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)

    print("[PROCESS] Calculating spatial constraints...")
    # 4. Process Control Variables
    MASTER_X, MASTER_Y, MASTER_Z = args.slot_size[0], args.grid_height, args.slot_size[1] # X, Y in render script is X and Z here. Slot Height is Y
    # Card
    # 73, 145, 50
    master_min = (args.slot_center[0] - MASTER_X/2, args.slot_center[1] - MASTER_Y/2, args.slot_center[2] - MASTER_Z/2)
    master_max = (args.slot_center[0] + MASTER_X/2, args.slot_center[1] + MASTER_Y/2, args.slot_center[2] + MASTER_Z/2)

    OVERLAP_Z = args.overlap_z 
    BOTTOM_THICKNESS = 1.0 # The fixed backing thickness for the UV print bed

    # 5. Generate specified jigs
    if args.jigs_requested:
        directions = [d.strip() for d in args.jigs_requested.split(",") if d.strip()]
    else:
        directions = ['+Z', '-Z', '+X', '-X', '+Y', '-Y']

    print(f"[PROCESS] Creating {len(directions)} jigs: {directions}")
    for d in directions:
        print(f"   -> Starting generation for {d}...")
        final_jig = generate_jig_in_place(
            raw_model=raw_model,
            master_min=master_min,
            master_max=master_max,
            overlap=OVERLAP_Z,
            bottom_thickness=BOTTOM_THICKNESS,
            inflation=args.inflation_margin,
            direction=d
        )
        
        # Export each individual jig STL
        bpy.ops.object.select_all(action='DESELECT')
        final_jig.select_set(True)
        bpy.context.view_layer.objects.active = final_jig
        stl_path = os.path.join(args.output_dir, f"{args.model_name_seed}_jig_{d}.stl")
        
        try:
            bpy.ops.export_mesh.stl(filepath=stl_path, use_selection=True)
        except Exception as e:
            print(f"      [WARN] Standard STL export failed: {e}. Falling back to binary writer...")
            _write_binary_stl_all(stl_path, final_jig)
        print(f"   -> Completed generation for {d}")

    print("[PROCESS] Exporting RAW Base Figure...")
    # 6. Export the RAW Base Figure
    bpy.ops.object.select_all(action='DESELECT')
    raw_model.select_set(True)
    bpy.context.view_layer.objects.active = raw_model
    figure_stl_path = os.path.join(args.output_dir, f"{args.model_name_seed}_figure.stl")
    try:
        bpy.ops.export_mesh.stl(filepath=figure_stl_path, use_selection=True)
    except Exception as e:
        print(f"Standard STL export for figure failed: {e}. Falling back to binary writer...")
        _write_binary_stl_all(figure_stl_path, raw_model)
    print(f"[OK] Base Figure STL Exported: {figure_stl_path}")
    
    print("[PROCESS] Saving Combined Blend File...")
    # 7. Save Combined Blend
    bpy.context.view_layer.update()
    bpy.ops.wm.save_as_mainfile(filepath=BLEND_OUTPUT_PATH)

    print("[PROCESS] Exporting Jigs Metadata...")
    import json
    meta_path = os.path.join(args.output_dir, f"{args.model_name_seed}_jigs_meta.json")
    bbox = [raw_model.matrix_world @ mathutils.Vector(b) for b in raw_model.bound_box]
    meta_data = {
        "master_size": {"x": MASTER_X, "y": MASTER_Y, "z": MASTER_Z},
        "figure_bounds": {
            "min_x": min(b.x for b in bbox), "min_y": min(b.y for b in bbox), "min_z": min(b.z for b in bbox),
            "max_x": max(b.x for b in bbox), "max_y": max(b.y for b in bbox), "max_z": max(b.z for b in bbox)
        }
    }
    with open(meta_path, 'w') as f:
        json.dump(meta_data, f, indent=4)

    print(f"[SUCCESS] Low-Profile Production Jig Generation Complete! Exiting.")
    import sys
    sys.exit(0)